# Generated by Django 5.1.4 on 2025-06-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0006_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
