# Generated by Django 5.1.4 on 2025-06-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeenotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeNotification',
        ),
    ]
